// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetCurrentUserWalletsResponse,
  CreateWalletResponse,
  GetUnifiedAccountsResponse,
  GetDirectRecipientsResponse,
  GetDirectRecipientByIdResponse,
  GetTransactionItemsResponse,
  GetTransactionItemByIdResponse,
  GetTransactionItemsByVirtualAccountIdResponse,
} from './types.gen'

const walletDtoSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  return data
}

export const getCurrentUserWalletsResponseTransformer = async (data: any): Promise<GetCurrentUserWalletsResponse> => {
  data = data.map((item: any) => {
    return walletDtoSchemaResponseTransformer(item)
  })
  return data
}

export const createWalletResponseTransformer = async (data: any): Promise<CreateWalletResponse> => {
  data = walletDtoSchemaResponseTransformer(data)
  return data
}

const directRecipientEntitySchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

export const getUnifiedAccountsResponseTransformer = async (data: any): Promise<GetUnifiedAccountsResponse> => {
  if (data.directRecipients) {
    data.directRecipients = data.directRecipients.map((item: any) => {
      return directRecipientEntitySchemaResponseTransformer(item)
    })
  }
  return data
}

export const getDirectRecipientsResponseTransformer = async (data: any): Promise<GetDirectRecipientsResponse> => {
  data = data.map((item: any) => {
    return directRecipientEntitySchemaResponseTransformer(item)
  })
  return data
}

export const getDirectRecipientByIdResponseTransformer = async (data: any): Promise<GetDirectRecipientByIdResponse> => {
  data = directRecipientEntitySchemaResponseTransformer(data)
  return data
}

const transactionItemResponseDtoSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  return data
}

const getTransactionItemsResponseDtoSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) => {
    return transactionItemResponseDtoSchemaResponseTransformer(item)
  })
  return data
}

export const getTransactionItemsResponseTransformer = async (data: any): Promise<GetTransactionItemsResponse> => {
  data = getTransactionItemsResponseDtoSchemaResponseTransformer(data)
  return data
}

export const getTransactionItemByIdResponseTransformer = async (data: any): Promise<GetTransactionItemByIdResponse> => {
  data = transactionItemResponseDtoSchemaResponseTransformer(data)
  return data
}

export const getTransactionItemsByVirtualAccountIdResponseTransformer = async (
  data: any
): Promise<GetTransactionItemsByVirtualAccountIdResponse> => {
  data = data.map((item: any) => {
    return transactionItemResponseDtoSchemaResponseTransformer(item)
  })
  return data
}
